spring:
  application:
    name: data-multidatasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 
    username: 
    password: 
  data-datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 
    username: 
    password: 

server:
  port: 9090
