spring:
  application:
    name: stream
  cloud:
    stream:
      bindings:
        voteInput:
          group: voteGroup
          destination: vote.exchange
          contentType: application/json
          binder: myrabbit1
        voteLogInput:
          group: logGroup
          destination: vote.exchange
          contentType: application/json
          binder: myrabbit1
        voteOutput:
          destination: vote.exchange
          contentType: application/json
          binder: myrabbit1
      binders:
        myrabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

server:
  port: 9090
